sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dokerfile"
  - docker build -t parkforte/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true parkforte/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success!"
